package com.wcl.mfnmanager.entities.player;

public enum PlayerPositionSkills {
    // BLOCKING SKILLS
    RUN_BLOCKING,
    PASS_BLOCKING,
    // CATCHING SKILLS
    PASS_CATCHING,
    BUMP_AND_RUN_AVOIDANCE,
    ROUTE_RUNNING,
    PASS_RECEPTION_COURAGE,
    // CORE SKILLS
    MAX_SPEED,
    ACCELERATION,
    STRENGTH,
    INTELLIGENCE,
    DISCIPLINE,
    // COVERAGE SKILLS
    PUNISH_RECEIVER,
    ZONE_DEFENCE,
    MAN_TO_MAN_COVERAGE,
    BUMP_AND_RUN_COVERAGE,
    // DEFENCE SKILLS
    STRIP_BALL,
    PASS_RUSH,
    RUN_DEFENCE,
    TACKLE_ABILITY,
    // HOLDER SKILLS
    HOLDING,
    // KICKING SKILLS
    KICK_STRENGTH,
    KICK_ACCURACY,
    // PASSING SKILLS
    PASS_ACCURACY,
    HARD_COUNT,
    ARM_STRENGTH,
    PASSING_RELEASE,
    LOOK_OFF_DEFENCE,
    SCRAMBLING,
    FIELD_OF_VISION,
    // PUNTING SKILLS
    PUNT_STRENGTH,
    PUNT_ACCURACY,
    PUNT_TIMING,
    // RETURN SKILLS
    KICK_CATCHING,
    // RUSHING SKILLS
    BREAK_TACKLE,
    BALL_CARRYING,
    AVOID_FUMBLE,
    // SNAPPING SKILLS
    SHORT_SNAPPING,
    LONG_SNAPPING;
}
