package com.wcl.mfnmanager.ui.controller.main;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.MenuItem;
import javafx.scene.layout.Pane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import org.controlsfx.control.StatusBar;
import com.wcl.mfnmanager.ui.Screen;
import com.wcl.mfnmanager.ui.controller.main.help.AboutController;
import com.wcl.mfnmanager.ui.utils.AbstractSwitchableDisplayController;
import com.wcl.mfnmanager.ui.utils.CustomFXMLLoader;
import com.wcl.mfnmanager.ui.utils.DisplaySwitcher;

import java.net.URL;
import java.util.ResourceBundle;


public final class MainController extends AbstractSwitchableDisplayController {

    @FXML
    private MenuItem closeAction;

    @FXML
    private StatusBar statusBar;

    private DisplaySwitcher<Screen, AbstractSwitchableDisplayController> displaySwitcher;

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        setStatus("Application running");
    }

    public void setDisplaySwitcher(DisplaySwitcher<Screen, AbstractSwitchableDisplayController> displaySwitcher) {
        this.displaySwitcher = displaySwitcher;
        this.displaySwitcher.setMainController(this);
    }

    /**
     * Processes the user selecting the Close menu item.
     * <p>
     * Shuts the application down.
     *
     * @param event the event generated by UI
     */
    public void handleCloseAction(final ActionEvent event) {
        System.exit(0);
    }

    public void handleContractCalculatorAction(final ActionEvent event) {
        setStatus("Contract calculator");
        displaySwitcher.loadDisplay(Screen.CONTRACT_CALCULATOR);
    }

    public void handleDownloadDraftClassesAction(final ActionEvent event) {
        setStatus("Downloading available draft classes");
        displaySwitcher.loadDisplay(Screen.DOWNLOAD_DRAFT_CLASSES);
    }

    public void handleViewDraftClassAction(final ActionEvent event) {
        setStatus("Draft Analysis");
        displaySwitcher.loadDisplay(Screen.VIEW_DRAFT_CLASS);
    }

    public void handleManualAction(final ActionEvent event) {
        final var loader = new CustomFXMLLoader<Pane, AboutController>();
        final var loadedElement = loader.loadFXML("/fxml/help/manual-dialog.fxml");
        final var stage = new Stage();
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setScene(new Scene(loadedElement.getElement()));
        stage.showAndWait();

    }

    public void handleAboutAction(final ActionEvent event) {
        final var loader = new CustomFXMLLoader<Pane, AboutController>();
        final var loadedElement = loader.loadFXML("/fxml/help/about-dialog.fxml");
        final var stage = new Stage();
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setScene(new Scene(loadedElement.getElement()));
        stage.showAndWait();
    }

    public void setStatus(final String text) {
        statusBar.setText(text);
    }
}
